### ISSUE TITLE
Users should be able to choose between XLSX or CSV as the output format

### ISSUE THREAD

**Issue by johardi** [metadatacenter/spreadsheet-validator-ui#7]
Currently, the tool automatically produces both formats and it is confusing

**Comment by muakdogan** [comment]
Multiple problems needs to be sorted out before being able to make this change.
If a zip file is uploaded to start with, variable "staticSheets" is never created so, app can't generate XLSX.
If an xlsx file is initially uploaded, generateNewSpreadsheet can't iterate over "staticSheets" resulting not being able to create XLSX again.
